training:
  epochs: 10
  batch_size: 4
  learning_rate: 1e-4
  lambda_feedback: 5.0
  output_dir: "checkpoints"  

data:
  annotations_csv: "data/annotations.csv"
  train_split: 0.8  

model:
  weights: "densenet121-res224-all"  

logging:
  use_tensorboard: true
  log_dir: "runs/offline_train"
